// Weather sound, through the park's audio engine (fx/audio/engine.js) once sound is on: loaded on the first weather
// that needs it (nothing audio is fetched before the sound button, and nothing at all in Clear). Sounds are generated by
// tools/audio/weather.py (data/audio/weather/, ~630 KB).
//   rain on paving / rain on the lake / rain drumming on a roof above the listener, mixed by where the listener is:
//   under cover (the park's top heights, scanned once on the CPU), near the lake (distance to its outline), high in the air
//   (a distant wash); wind (Storm, a little in Rain and Snow); thunder after each lightning flash, late by distance at
//   343 m/s, darker and quieter the farther it is, panned toward the flash. Music and ambience duck a little in heavy rain.
// Everything goes into the engine's ambience bus, so the "Ambience & effects" switch and the volume apply.
const FILES = { open: 'rain_open', lake: 'rain_lake', roof: 'rain_roof', wind: 'wind' };
const LOOP = { open: [0.5, 16.5], lake: [0.5, 16.5], roof: [0.5, 14.5], wind: [0.5, 18.5] };
const THUNDER = ['thunder_1', 'thunder_2', 'thunder_3'];
const C = 343;
const clamp = (v, a, b) => Math.min(b, Math.max(a, v));
const sstep = (a, b, x) => { const t = clamp((x - a) / (b - a), 0, 1); return t * t * (3 - 2 * t); };

export function createWeatherAudio({ THREE, camera, fetchBin, getEngine, getPark, getMode, getWalk, manifest }) {
  const st = { ready: false, err: null, voices: 0, cover: 0, lake: 0, duck: 1, bytes: 0, thunders: 0 };
  const buf = {}; let ctx = null, N = null, bus = null, lp = null; const ch = {};
  let lastSeq = 0, grid = null, tick = 0, quietFor = 0;

  async function load(eng) {
    ctx = eng.debug.ctx; N = eng.debug.nodes;
    const dec = async (name) => { const u8 = await fetchBin('audio/weather/' + name + '.m4a'); st.bytes += u8.length; return ctx.decodeAudioData(u8.buffer.slice(u8.byteOffset, u8.byteOffset + u8.length)); };
    const names = [...Object.values(FILES), ...THUNDER];
    const out = await Promise.all(names.map((n) => dec(n).catch(() => null)));
    names.forEach((n, i) => { buf[n] = out[i]; });
    bus = ctx.createGain(); bus.gain.value = 1; bus.connect(N.amb);
    lp = ctx.createBiquadFilter(); lp.type = 'lowpass'; lp.frequency.value = 16000; lp.Q.value = 0.5; lp.connect(bus);
    st.ready = true;
  }
  const starting = (() => { const e = getEngine(); return e && e.debug && e.debug.ctx ? load(e).catch((e2) => { st.err = String(e2); }) : null; })();

  function start(k) {
    const b = buf[FILES[k]]; if (!b) return null;
    const g = ctx.createGain(); g.gain.value = 0;
    const s = ctx.createBufferSource(); s.buffer = b; s.loop = true; s.loopStart = LOOP[k][0]; s.loopEnd = Math.min(LOOP[k][1], b.duration);
    s.connect(g); g.connect(k === 'roof' ? bus : lp);                  // rain heard from under a roof goes through the muffler
    s.start(0, LOOP[k][0] + Math.random() * (LOOP[k][1] - LOOP[k][0]));
    return { s, g };
  }
  function stopAll() { const now = ctx.currentTime; for (const k in ch) { const c = ch[k]; c.g.gain.setTargetAtTime(0, now, 0.1); c.s.stop(now + 0.6); delete ch[k]; } }

  // what is over the listener: the park's triangles scanned once on the CPU into a 512 x 512 grid of top heights (a few
  // tens of thousands of triangles per frame; reading the GPU cover map back would stall the pipeline)
  const S = 512, R = 384, scan = { meshes: null, mi: 0, ti: 0, g: null, parts: -1 };
  function scanStep(budget) {
    const park = getPark && getPark(); if (!park) return;
    if (!scan.meshes) { if (park.children.length === scan.parts) return; scan.parts = park.children.length; scan.meshes = park.children.filter((o) => o.isMesh && o.geometry.attributes.aCol && o.geometry.index); scan.mi = scan.ti = 0; scan.g = new Float32Array(S * S).fill(-8); }
    const g = scan.g, k = S / (2 * R);
    while (budget > 0 && scan.mi < scan.meshes.length) {
      const m = scan.meshes[scan.mi], p = m.geometry.attributes.position.array, idx = m.geometry.index.array, o = m.position, sc = m.scale.x;
      const T = idx.length / 3, end = Math.min(T, scan.ti + budget);
      for (let t = scan.ti; t < end; t++) {
        const a = idx[t * 3] * 3, b = idx[t * 3 + 1] * 3, c = idx[t * 3 + 2] * 3;
        const ya = Math.max(p[a + 1], p[b + 1], p[c + 1]) * sc + o.y;
        const x0 = Math.min(p[a], p[b], p[c]) * sc + o.x, x1 = Math.max(p[a], p[b], p[c]) * sc + o.x;
        const z0 = Math.min(p[a + 2], p[b + 2], p[c + 2]) * sc + o.z, z1 = Math.max(p[a + 2], p[b + 2], p[c + 2]) * sc + o.z;
        const i0 = Math.max(0, Math.floor((x0 + R) * k)), i1 = Math.min(S - 1, Math.floor((x1 + R) * k));
        const j0 = Math.max(0, Math.floor((R - z1) * k)), j1 = Math.min(S - 1, Math.floor((R - z0) * k));
        if (i1 - i0 > 24 || j1 - j0 > 24) continue;                    // huge sheets (terrain): not a roof
        for (let j = j0; j <= j1; j++) for (let i = i0; i <= i1; i++) { const q = j * S + i; if (g[q] < ya) g[q] = ya; }
      }
      budget -= end - scan.ti; scan.ti = end;
      if (end >= T) { scan.mi++; scan.ti = 0; }
    }
    if (scan.mi >= scan.meshes.length) { grid = scan.g; scan.meshes = null; }
  }
  function roofAt(x, z) {            // three.js x, z -> top height (m), or -8
    if (!grid) return -8;
    const i = Math.floor((x / (2 * R) + 0.5) * S), j = Math.floor((-z / (2 * R) + 0.5) * S);
    return i < 0 || j < 0 || i >= S || j >= S ? -8 : grid[j * S + i];
  }
  function lakeDist(x, y) {          // Blender x, y: 0 inside the lake, else distance to its outline
    const pl = manifest && manifest().lake; if (!pl) return 1e9;
    let inside = false, d2 = 1e18;
    for (let i = 0, j = pl.length - 1; i < pl.length; j = i++) {
      const [xi, yi] = pl[i], [xj, yj] = pl[j];
      if ((yi > y) !== (yj > y) && x < (xj - xi) * (y - yi) / (yj - yi) + xi) inside = !inside;
      const ex = xj - xi, ey = yj - yi, t = clamp(((x - xi) * ex + (y - yi) * ey) / (ex * ex + ey * ey || 1), 0, 1);
      d2 = Math.min(d2, (xi + t * ex - x) ** 2 + (yi + t * ey - y) ** 2);
    }
    return inside ? 0 : Math.sqrt(d2);
  }

  const _r = new THREE.Vector3(), _d = new THREE.Vector3(), _p = new THREE.Vector3();
  function update(dt, time, now, shade) {
    const eng = getEngine();
    if (!st.ready || !eng || !ctx) return !Object.keys(ch).length;
    scanStep(40000);
    const t = ctx.currentTime, est = eng.debug.st;
    const rain = Math.min(1, now.rain / 1.6) * 1.6, active = rain > 0.002 || now.wind > 0.002 || now.snow > 0.002;
    if (active) for (const k in FILES) if (!ch[k]) { const c = start(k); if (c) ch[k] = c; }
    if ((tick -= dt) <= 0) {                                       // place: 4 times a second is plenty
      tick = 0.25;
      // where the ears are: the walker's head in Walk mode (Wick's camera rides ~6 m behind and above him), else the camera
      const wk = getMode && getMode() === 'walk' && getWalk ? getWalk() : null;
      const p = wk ? _p.set(wk.x, wk.z + 1.6, -wk.y) : camera.position, roof = roofAt(p.x, p.z);
      st.cover += ((roof > p.y + 0.4 ? 1 : 0) - st.cover) * 0.5;
      st.lake = sstep(45, 4, lakeDist(p.x, -p.z));
    }
    const h = Math.max(0, camera.position.y - 2), air = sstep(15, 120, h), cov = st.cover;
    const gOpen = 0.55 * Math.min(1, rain) * (1 - 0.45 * st.lake) * (1 - 0.6 * air) + 0.15 * Math.max(0, rain - 1);
    const gLake = 0.55 * Math.min(1, rain) * st.lake * (1 - air) * (1 - 0.7 * cov);
    const gRoof = 0.6 * Math.min(1, rain) * cov * (1 - air);
    const gWind = 0.5 * now.wind + 0.12 * now.snow;
    // duck the park's music and ambience a little in heavy rain (and lift the rain by as much, it shares the bus)
    const duck = 1 - 0.22 * sstep(0.4, 1.6, now.rain) - 0.1 * now.wind;
    st.duck = duck;
    if (ch.open) ch.open.g.gain.setTargetAtTime(gOpen * (1 - 0.5 * cov), t, 0.3);
    if (ch.lake) ch.lake.g.gain.setTargetAtTime(gLake, t, 0.4);
    if (ch.roof) ch.roof.g.gain.setTargetAtTime(gRoof, t, 0.3);
    if (ch.wind) ch.wind.g.gain.setTargetAtTime(gWind, t, 0.6);
    lp.frequency.setTargetAtTime(16000 * (1 - 0.92 * cov) * (1 - 0.7 * air) + 400, t, 0.3);
    bus.gain.setTargetAtTime(1 / duck, t, 0.5);
    N.music.gain.setTargetAtTime((est.music ? 1 : 0) * duck, t, 0.5);
    N.amb.gain.setTargetAtTime((est.ambience ? 1 : 0) * duck, t, 0.5);
    // thunder: late by distance, darker and quieter the farther, from the flash's side
    const L = shade && shade.lightning && shade.lightning.last;
    if (L && L.seq !== lastSeq) {
      lastSeq = L.seq; const b = buf[THUNDER[L.seq % THUNDER.length]];
      if (b && est.enabled) {
        const s = ctx.createBufferSource(), g = ctx.createGain(), f = ctx.createBiquadFilter(), pan = ctx.createStereoPanner ? ctx.createStereoPanner() : null;
        s.buffer = b; s.playbackRate.value = 0.85 + 0.3 * Math.random();
        g.gain.value = clamp(700 / L.dist, 0.3, 1.1) * 0.9;
        f.type = 'lowpass'; f.frequency.value = 250 + 3500 * Math.exp(-L.dist / 500);
        s.connect(f); f.connect(g);
        camera.matrixWorld.extractBasis(_r, _d, _d); if (pan) { pan.pan.value = clamp(L.dir.dot(_r), -1, 1) * 0.7; g.connect(pan); pan.connect(bus); } else g.connect(bus);
        s.start(t + L.dist / C); s.onended = () => { s.disconnect(); g.disconnect(); if (pan) pan.disconnect(); };
        st.thunders++;
      }
    }
    // all quiet for a while: stop the loops and hand the buses back untouched
    if (!active && duck === 1) {
      quietFor += dt;
      if (quietFor > 2 && Object.keys(ch).length) { stopAll(); N.music.gain.setTargetAtTime(est.music ? 1 : 0, t, 0.2); N.amb.gain.setTargetAtTime(est.ambience ? 1 : 0, t, 0.2); bus.gain.setTargetAtTime(1, t, 0.2); }
    } else quietFor = 0;
    st.voices = Object.keys(ch).length;
    return !st.voices;
  }
  return { update, st, roofAt, lakeDist, get starting() { return starting; } };
}
